Annotations patch
vpa-research/libsl-parser pull request #4
Opened 2023-03-24 07:32 UTC by chernyiv

1. Annotation declarations were added. Declared annotations and annotations which are used in segments of specification are not the same entities.
2. Function, function parameters and automaton annotations were added and enhanced.
3. Multiple annotations are now allowed.

2023-03-25 09:27 UTC, vldF commented
Wrong target branch is set

2023-03-25 10:31 UTC, vldF requested changes

2023-03-25 10:31 UTC, vldF commented on src/main/antlr/LibSLParser.g4
> + * syntax: annotation Something(
What do you think about make brackets optional in the case of empty parameters? I made this for automaton, so this could make the syntax more consistent

2023-03-25 10:31 UTC, vldF commented on src/main/antlr/LibSLParser.g4
> +   :   nameWithType (EQ assignmentRight)?
Be careful: after https://github.com/vpa-research/libsl-parser/pull/2 will be merged this code should be upgraded (to change `EQ` to `ASSIGN_OP`)

2023-03-25 10:31 UTC, vldF commented on src/main/antlr/LibSLParser.g4
> + * syntax: @Annotation
Please, show here the fact of annotations are optional and plural here

2023-03-25 10:31 UTC, vldF commented on src/main/antlr/LibSLParser.g4
> +functionParamAnnotations
what the differ between `functionParamAnnotations` and `functionParamAnnotations`

2023-03-25 10:31 UTC, vldF commented on src/main/kotlin/org/jetbrains/research/libsl/context/LslContextBase.kt
> +    fun storeAnnotation(annotation: Annotation) {
I think there is a miscommunication between us. As far as I know `storeAnnotation` is used to store annotations while they are being found. This action (prove me wrong) is useless

When we discussed the strategy of annotations resolution, I supposed to store only annotations declaration and store for every annotation usage only reference to it in corresponding node

2023-03-25 10:31 UTC, vldF commented on src/main/kotlin/org/jetbrains/research/libsl/nodes/annotations.kt
> +        TODO("Not yet implemented")
Why?

2023-03-25 10:31 UTC, vldF commented on src/main/kotlin/org/jetbrains/research/libsl/context/LslContextBase.kt
> +    fun storeAnnotation(annotation: Annotation) {
You have no link between annotation declarations and usages now (as far as I know)

2023-03-25 10:31 UTC, vldF commented on src/main/kotlin/org/jetbrains/research/libsl/nodes/references/builders/AnnotationReferenceBuilder.kt
> +}
Empty new line is missing here (I will add this inspection to Qodana lately)

2023-03-25 10:31 UTC, vldF commented on src/main/kotlin/org/jetbrains/research/libsl/nodes/variables.kt
> +
I think this empty line is useless here :)

2023-03-25 10:31 UTC, vldF commented on src/main/kotlin/org/jetbrains/research/libsl/visitors/AutomatonResolver.kt
> +    private fun makeAutomatonAnnotationList(ctx: List<LibSLParser.AutomatonAnnotationsContext>?): MutableList<AnnotationReference>? {
Please, use more conventional name patterns like `getAutomatonAnnotationList`, `createAutomatonAnnotationList` or `buildAutomatonAnnotationList`

(I'd use the first one here)

2023-03-25 10:31 UTC, vldF commented on src/main/kotlin/org/jetbrains/research/libsl/visitors/AutomatonResolver.kt
> +    private fun makeAutomatonAnnotationList(ctx: List<LibSLParser.AutomatonAnnotationsContext>?): MutableList<AnnotationReference>? {
Also, may be you should make every property contains annotations in `node`s non-nullable. To show that there are no annotations you could use an empty collection

2023-03-25 10:31 UTC, vldF commented on src/main/kotlin/org/jetbrains/research/libsl/visitors/AutomatonResolver.kt
> +    private fun makeAutomatonAnnotationList(ctx: List<LibSLParser.AutomatonAnnotationsContext>?): MutableList<AnnotationReference>? {
Nullable collections is a code smell

2023-03-25 10:31 UTC, vldF commented on src/main/kotlin/org/jetbrains/research/libsl/visitors/FunctionVisitor.kt
> +            return AnnotationReference("target", context)
Could you refactor out `@Target` annotation to some singleton variable? This could help in future refactoring

2023-03-25 10:31 UTC, vldF commented on src/main/kotlin/org/jetbrains/research/libsl/visitors/FunctionVisitor.kt
> +                it.resolveOrError().name == "target"} ?: false } ?: return null
If you move out `@Target` annotation (see previous comment), this check cold be replaced with something like `it.resolveOrError() == TargetAnnotationHelper.targetAnnotation`

2023-03-25 10:31 UTC, vldF commented on src/main/kotlin/org/jetbrains/research/libsl/visitors/TopLevelDeclarationsResolver.kt
> +    //TODO annotations
Todos are bad in PRs

2023-03-25 10:31 UTC, vldF commented on src/test/testdata/lsl/annotationDeclaration.lsl
> +
To many empty lines

2023-03-25 10:31 UTC, vldF commented on src/test/testdata/lsl/annotations.lsl
> +    fun f(@anno param: Int);
So, this code is wrong because there is no `@anno` annotation declaration

2023-03-25 10:31 UTC, vldF commented on src/test/testdata/lsl/automatonAnnotations.lsl
> +@Public
Wrong code again

2023-03-25 10:31 UTC, vldF commented on src/test/testdata/lsl/automatonAnnotations.lsl
> +@Public
Some other tests are wrong too

2023-03-27 14:06 UTC, chernyiv commented on src/main/antlr/LibSLParser.g4
> + * syntax: annotation Something(
Made brackets optional in [f040ef9](https://github.com/vpa-research/libsl-parser/pull/4/commits/f040ef9336b5c6300c08b0b14d1fa23d571ab45d)

2023-03-27 14:07 UTC, chernyiv commented on src/main/kotlin/org/jetbrains/research/libsl/visitors/TopLevelDeclarationsResolver.kt
> +    //TODO annotations
Removed TODOs in [f040ef9](https://github.com/vpa-research/libsl-parser/pull/4/commits/f040ef9336b5c6300c08b0b14d1fa23d571ab45d)

2023-03-27 16:05 UTC, chernyiv commented on src/main/antlr/LibSLParser.g4
> +   :   nameWithType (EQ assignmentRight)?
Merged develop into annotations-patch and fixed the operator issue

2023-03-27 16:24 UTC, chernyiv commented on src/main/antlr/LibSLParser.g4
> +functionParamAnnotations
Fixed issue in [e9279a2](https://github.com/vpa-research/libsl-parser/pull/4/commits/e9279a2dd07e29d5b4f376b65ef6901e7b69d8e8). Now only `functionAnnotations` are used.

2023-03-27 16:33 UTC, chernyiv commented on src/main/antlr/LibSLParser.g4
> + * syntax: @Annotation
Done

2023-03-29 07:14 UTC, vldF commented
You have fallen tests, fix it before merge

2023-03-29 07:20 UTC, vldF requested changes

2023-03-29 07:20 UTC, vldF commented on src/main/kotlin/org/jetbrains/research/libsl/nodes/annotations.kt
> +            append(")")
This code adds an closing `)` at the line of the last parameter. I'd add a line break before it:
```
@Anno(
    param1,
    param2
)
```

2023-05-18 10:59 UTC, closed without merging